---

api_host: pve
api_password: "{{ lookup('file', '../vault/api_password') }}"  # path relative to playbook
node: pve  # Name of Proxmox host

defaults:
  password: "{{ lookup('file', '../vault/root_ct_pass') }}"  # path relative to playbook
  disk: "zfs-proxmox:8"  # disk_volume key was unsuccessful
  cores: 1
  cpus: 1
  memory: 1024
  swap: 1024
  ostemplate: "zfs-proxmox:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.zst"
  searchdomain: 'site.domain'
  nameserver: '1.1.1.1,8.8.8.8'
  netif: '{"net0":"name=eth0,ip=dhcp,ip6=dhcp,bridge=vmbr0"}'
  pubkey: "{{ lookup('file', '../vault/proxmox_pubkey') }}"  # path relative to playbook
  state: present
  onboot: true
