- name: Add an initial user to new LXC containers
  hosts: containers  # janky
  tasks:
    - name: Add user "api_user" to container(s)
      user:
        name: '{{ api_user }}'
        password: "{{ default_password | password_hash('sha512') }}"
        group: sudo
        create_home: yes
        generate_ssh_key: true  # defaults to RSA key at .ssh/id_rsa
