---
- hosts: containers
  remote_user: '{{ api_user }}'
  roles:
    - ct_base

- hosts: test.container
  remote_user: '{{ api_user }}'
  become: true
  roles:
    - test.container

- hosts: duplicate.ct
  remote_user: '{{ api_user }}'
  become: true
  roles:
    - duplicate.ct

- hosts: bare-bones
  remote_user: '{{ api_user }}'
  roles:
    - bare-bones
