---
- name: Configure basic container
  hosts: containers
  remote_user: '{{ api_user }}'
  roles:
    - ct_base

- name: Configure container specifics
  hosts: containers
  remote_user: '{{ api_user }}'
  become: true
  roles:
    - test.container

- hosts: duplicate.ct
  remote_user: '{{ api_user }}'
  become: true
  roles:
    - duplicate.ct

- hosts: bare-bones
  remote_user: '{{ api_user }}'
  roles:
    - bare-bones
