---
- name: Create new LXC container in Proxmox
  hosts: proxmox
  tasks:
    - name: Create LXC Containers
      proxmox:
        api_host: pve
        api_user: ansible_pm@pam  # Proxmox user, -u ANSIBLE_USER on command line
        api_password: ansible  # Password in plaintext !!!
        node: pve  # Name of Proxmox host
        hostname: test.container
        vmid: 123  # Specifying Container ID
        password: P@ssw0rd  # Password in plaintext !!!
        disk: "zfs-proxmox:8"  # disk_volume key was unsuccessful
        cores: 1
        cpus: 1
        memory: 1024
        swap: 1024
        ostemplate: "zfs-proxmox:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.zst"
        #searchdomain
        nameserver: 8.8.8.8
        netif: '{"net0":"name=eth0,ip=192.168.0.123/24,bridge=vmbr0"}'
        #pubkey
        #onboot
        state: present
      with_items: '{{ groups["containers"] }}'  # from inventory
      loop_control:
        pause: 5
      register: created_containers

    - name: sleep
      pause:
        seconds: 10
      when: created_containers.changed

    - name: Start container(s)
      proxmox:
        api_host: '{{ api_host }}'
        api_user: '{{ api_user }}'
        api_password: '{{ api_password }}'
        node: '{{ node }}'
        hostname: '{{ hostvars[item.item].inventory_hostname }}'
        state: 'started'
      with_items: '{{ created_containers.results }}'
      when: created_containers.changed

    - name: sleep
      pause:
        seconds: 10
      when: created_containers.changed
