---
- name: Create new LXC container in Proxmox
  hosts: proxmox
  tasks:
    - name: Create LXC Containers
      proxmox:
        api_host: '{{ api_host }}'
        api_user: '{{ api_user }}'
        api_password: '{{ api_password }}'
        node: '{{ node }}'
        hostname: '{{ hostvars[item]["inventory_hostname"] }}'
        vmid: '{{ hostvars[item].vmid }}'  # Must be specified in host_vars/<hostname>.yaml
        password: '{{ hostvars[item].password | default(defaults.password) }}'
        disk: '{{ hostvars[item].disk | default(defaults.disk) }}'
        cores: '{{ hostvars[item].cores | default(defaults.cores) }}'
        cpus: '{{ hostvars[item].cpus | default(defaults.cpus) }}'
        memory: '{{ hostvars[item].memory | default(defaults.memory) }}'
        swap: '{{ hostvars[item].swap | default(defaults.swap) }}'
        ostemplate: '{{ hostvars[item].ostemplate | default(defaults.ostemplate) }}'
        searchdomain: '{{ hostvars[item].searchdomain | default(defaults.searchdomain) }}'
        nameserver: '{{ hostvars[item].nameserver | default(defaults.nameserver) }}'
        netif: '{{ hostvars[item].netif | default(defaults.netif) }}'
        pubkey: '{{ hostvars[item].pubkey | default(defaults.pubkey) }}'
        state: '{{ hostvars[item].state | default(defaults.state) }}'
        onboot: '{{ hostvars[item].onboot | default(defaults.onboot) }}'
      with_items: '{{ groups["containers"] }}'  # from inventory
      loop_control:
        pause: 5
      register: created_containers

    - name: sleep
      pause:
        seconds: 10
      when: created_containers.changed

    - name: Start container(s)
      proxmox:
        api_host: '{{ api_host }}'
        api_user: '{{ api_user }}'
        api_password: '{{ api_password }}'
        node: '{{ node }}'
        hostname: '{{ hostvars[item.item].inventory_hostname }}'
        state: 'started'
      with_items: '{{ created_containers.results }}'
      when: created_containers.changed

    - name: sleep
      pause:
        seconds: 10
      when: created_containers.changed
