---
- name: Create new LXC container in Proxmox
  hosts: pve
  tasks:
    - name: Create LXC Container with minimal options
      proxmox:
        vmid: 123  # Specifying Container ID
        node: pve  # Name of Proxmox host
        api_user: ansible_pm@pam  # Proxmox user, -u ANSIBLE_USER on command line
        api_password: ansible  # Password in plaintext !!!
        api_host: pve
        hostname: test.container
        password: P@ssw0rd  # Password in plaintext !!!
        ostemplate: "zfs-proxmox:vztmpl/ubuntu-22.04-standard_22.04-1_amd64.tar.zst"
        state: present
