---
- name: Create new LXC container in Proxmox with minimal options
  hosts: proxmox
  remote_user: '{{ api_user }}'
  tasks:
    - name: Create LXC Container with minimal options
      proxmox:
        api_host: '{{ api_host }}'
        api_user: '{{ api_user }}@pam'
        api_password: '{{ api_password }}'
        node: '{{ node }}'
        hostname: "container-{{ lookup('password', '/dev/null chars=ascii_lowercase,digits length=8') }}"  # Thanks, NetworkChuck
        vmid: '{{ vmid }}'  # Specifying on CLI with [--extra-vars "vmid=124"]
        password: '{{ password | default(defaults.password) }}'
        disk: '{{ disk | default(defaults.disk) }}'
        cores: '{{ cores | default(defaults.cores) }}'
        cpus: '{{ cpus | default(defaults.cpus) }}'
        memory: '{{ memory | default(defaults.memory) }}'
        swap: '{{ swap | default(defaults.swap) }}'
        ostemplate: '{{ ostemplate | default(defaults.ostemplate) }}'
        searchdomain: '{{ searchdomain | default(defaults.searchdomain) }}'
        nameserver: '{{ nameserver | default(defaults.nameserver) }}'
        netif: '{{ netif | default(defaults.netif) }}'
        pubkey: '{{ pubkey | default(defaults.pubkey) }}'
        state: '{{ state | default(defaults.state) }}'
        onboot: '{{ onboot | default(defaults.onboot) }}'
