---
- name: Prepare Proxmox host
  hosts: proxmox
  vars:
      pip_packages:
        - python3-pip
        - build-essential
  tasks:
    - name: disable enterprise repos
      apt_repository:
        repo: 'deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise'
        state: absent
    - name: switch to community repos
      apt_repository:
        repo: 'deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription'
        state: present
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
    - name: Install pip packages
      apt:
        name: "{{ pip_packages }}"
        state: latest
    - name: Install virtualenv
      apt:
        name: virtualenv
        state: latest
    - name: Install proxmoxer
      apt:
        name: python3-proxmoxer
        state: latest
    - name: Install requests
      apt:
        name: python3-requests
        state: latest

- name: Prepare Proxmox user
  hosts: proxmox
  tasks:
    - name: Add user "api_user" to Proxmox host
      user:
        name: '{{ api_user }}'
        password: "{{ api_password | password_hash('sha512') }}"  # must be the hashed version
        group: sudo
        create_home: yes
        generate_ssh_key: true  # defaults to RSA key at .ssh/id_rsa
