---
- name: Prepare Proxmox repositories
  hosts: proxmox
  remote_user: root
  tasks:
    - name: Disable enterprise repos
      apt_repository:
        repo: 'deb https://enterprise.proxmox.com/debian/pve bookworm pve-enterprise'
        state: absent
    - name: Switch to community repos
      apt_repository:
        repo: 'deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription'
        state: present

- name: Prepare Proxmox user
  hosts: proxmox
  remote_user: root
  tasks:
    - name: Install sudo
      apt:
        name: sudo
        state: latest
    - name: Add user "api_user" to Proxmox host
      user:
        name: '{{ api_user }}'
        password: "{{ api_password | password_hash('sha512') }}"  # must be the hashed version
        group: sudo
        create_home: yes
        generate_ssh_key: true  # defaults to RSA key at .ssh/id_rsa
    - name: Set authorized key taken from local user's file
      authorized_key:
        user: '{{ api_user }}'
        state: present
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name: Prepare Proxmox packages
  hosts: proxmox
  remote_user: '{{ api_user }}'
  become: true
  vars:
      pip_packages:
        - python3-pip
        - build-essential
  tasks:
    - name: Update all packages to the latest version
      apt:
        upgrade: dist
    - name: Install pip packages
      apt:
        name: "{{ pip_packages }}"
        state: latest
    - name: Install virtualenv
      apt:
        name: virtualenv
        state: latest
    - name: Install proxmoxer
      apt:
        name: python3-proxmoxer
        state: latest
    - name: Install requests
      apt:
        name: python3-requests
        state: latest
