---
- name: Remove an LXC container from Proxmox
  hosts: proxmox
  gather_facts: false
  tasks:
    - name: Stop LXC Container
      proxmox:
        vmid: '{{ vmid }}'  # Specifying on CLI with [--extra-vars "vmid=124"]
        api_host: '{{ api_host }}'
        api_user:  '{{ api_user }}@pam'
        api_password: '{{ api_password }}'
        node: '{{ node }}'
        state: stopped

    - name: sleep
      pause:
        seconds: 5

    - name: Remove LXC Container
      proxmox:
        vmid: '{{ vmid }}'  # Specifying on CLI with [--extra-vars "vmid=124"]
        api_host: '{{ api_host }}'
        api_user:  '{{ api_user }}@pam'
        api_password: '{{ api_password }}'
        node: '{{ node }}'
        state: absent
